plugins {
    id 'java'
}

group = 'fr.pickaria'
version = '1.7.0'

repositories {
    mavenCentral()
}

dependencies {
}

def targetJavaVersion = 17
java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

jar {
    archiveFileName = "${project.name}-${project.version}.jar"
}
