name: Build and Publish Jar Artifact

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/push.yml'
      - 'gradle/**'
      - 'src/**'
      - '*/src/**'
      - 'build.gradle'
      - '*/build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build All Jars
        run: ./gradlew jar

      - name: Upload Root Project Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: root-jar-artifact
          path: build/libs/*.jar
        if: hashFiles('build/libs/*.jar') != ''

      - name: Upload Subproject Jar Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subproject-jar-artifacts
          path: '*/build/libs/*.jar'
        if: hashFiles('*/build/libs/*.jar') != ''
